# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebfcc3ff95a951a194b17ed6489048452ab38cb4acc99cacc9ccd569f3387550c2ea69e10f872717f108e8eb0e5016af6053d552ebe1e24fc7aa26ff87bed052

test:
  secret_key_base: 34050a923053a954216a64e61a7d1bbd60e05f2bdad9fe46879ca10d9792deaa25ff97b7b6ffc09043d3823e9bfc1e78dac76ee44dcceed00553765ec29dbcce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
